In [9]:
import pandas as pd
import numpy as np

### Series
Series是一个包含一系列值的一维数组对象和一个关联的数据标签（index）  
pd.Series类似于np.array，pd.Series主要是用于构建含有标签的一维数组

In [10]:
obj = pd.Series([4, 7, -5, 3], index=list('ABCD'), name='score', dtype=np.int16)
obj

A    4
B    7
C   -5
D    3
Name: score, dtype: int16

Series.values 获取Series的值  
Series.index 获取Series的索引

In [7]:
obj.values, obj.index

(array([ 4,  7, -5,  3]), Index(['A', 'B', 'C', 'D'], dtype='str'))

相比于Numpy，可以使用标签对单个值或一组值进行访问

In [11]:
obj['A'], obj[['A', 'C', 'D']]

(np.int16(4),
 A    4
 C   -5
 D    3
 Name: score, dtype: int16)

使用Boolean数组进行过滤

In [12]:
obj2 = pd.Series([4, 7, -5, 3], index=['d', 'b', 'a', 'c'])

In [15]:
np.exp(obj2)

d      54.598150
b    1096.633158
a       0.006738
c      20.085537
dtype: float64

Series可以看做是字典，所以可以用in来判断是否包含有个标签，以及可以通过字典来创建Series

In [18]:
sdata = {'Ohio': 35000, 'Texas': 71000, 'Oregon': 16000, 'Utah': 5000}
obj3 = pd.Series(sdata)
obj3

Ohio      35000
Texas     71000
Oregon    16000
Utah       5000
dtype: int64

isnull和notnull用于检查是否为缺失值

In [31]:
data = {'state': ['Ohio', 'Ohio', 'Ohio', 'Nevada', 'Nevada', 'Nevada'],
'year': [2000, 2001, 2002, 2001, 2002, 2003],
'pop': [1.5, 1.7, 3.6, 2.4, 2.9, 3.2]}

frame = pd.DataFrame(data, columns=['year', 'state', 'pop'], index=['one', 'two', 'three', 'four', 'five', 'six'])
frame

       year   state  pop
one    2000    Ohio  1.5
two    2001    Ohio  1.7
three  2002    Ohio  3.6
four   2001  Nevada  2.4
five   2002  Nevada  2.9
six    2003  Nevada  3.2

In [36]:
val = pd.Series([-1.2, -1.5, -1.7], index=['two', 'three', 'four'])
frame['debt'] = val
frame

       year   state  pop  debt
one    2000    Ohio  1.5   NaN
two    2001    Ohio  1.7  -1.2
three  2002    Ohio  3.6  -1.5
four   2001  Nevada  2.4  -1.7
five   2002  Nevada  2.9   NaN
six    2003  Nevada  3.2   NaN

In [39]:
frame = pd.DataFrame(np.arange(9).reshape((3, 3)),
                      index=['a', 'c', 'd'],
                      columns=['Ohio', 'Texas', 'California'])

frame2 = frame.reindex(['a', 'b', 'c', 'd'], method='ffill')
frame2

   Ohio  Texas  California
a     0      1           2
b     0      1           2
c     3      4           5
d     6      7           8

In [ ]:
frame2['Ohio']

np.int64(0)

In [54]:
ser = pd.Series(np.arange(3.), index=['a', 'b', 'c'])
ser.iloc[-1]

np.float64(2.0)